version: "3.8"

services:

  redis-db:
    image: redis:7
    container_name: iss_tracker_redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped

  flask-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: iss_tracker_app
    ports:
      - "5000:5000"
    depends_on:
      - redis-db
    volumes:
      - ./data:/data
    restart: unless-stopped
